// desktop/src/renderer-vue/src/knowledge-desk/components/VirtualList.vue
<script setup lang="ts" generic="T">
import { computed, ref, type ComponentPublicInstance } from 'vue'
import { useVirtualizer } from '@tanstack/vue-virtual'

// Multi-root component (empty slot vs list): bind $attrs explicitly so a caller
// supplied class reaches the scroll container.
defineOptions({ inheritAttrs: false })

const props = withDefaults(
  defineProps<{
    items: T[]
    estimateSize?: number
    overscan?: number
  }>(),
  {
    estimateSize: 120,
    overscan: 5,
  },
)

const parentRef = ref<HTMLDivElement | null>(null)

// Pass the whole options object as a computed ref: @tanstack/vue-virtual accepts
// MaybeRef<options> and re-applies it when the dependency (items.length) changes.
const virtualizer = useVirtualizer<HTMLDivElement, HTMLDivElement>(
  computed(() => ({
    count: props.items.length,
    getScrollElement: () => parentRef.value,
    estimateSize: () => props.estimateSize,
    overscan: props.overscan,
  })),
)

const virtualItems = computed(() => virtualizer.value.getVirtualItems())
const totalSize = computed(() => virtualizer.value.getTotalSize())

function measureItem(el: Element | ComponentPublicInstance | null) {
  virtualizer.value.measureElement((el ?? null) as HTMLDivElement | null)
}
</script>

<template>
  <slot v-if="items.length === 0" name="empty" />
  <div v-else ref="parentRef" v-bind="$attrs" class="kd-virtual-list">
    <div :style="{ height: `${totalSize}px`, position: 'relative' }">
      <div
        v-for="virtualItem in virtualItems"
        :key="String(virtualItem.key)"
        :ref="measureItem"
        :data-index="virtualItem.index"
        :style="{
          position: 'absolute',
          top: 0,
          left: 0,
          width: '100%',
          transform: `translateY(${virtualItem.start}px)`,
        }"
      >
        <slot :item="items[virtualItem.index]" :index="virtualItem.index" />
      </div>
    </div>
  </div>
</template>

// desktop/src/renderer/src/knowledge-desk/components/VirtualList.tsx
import { useRef, useMemo } from 'react';
import { useVirtualizer } from '@tanstack/react-virtual';
import type { ReactNode } from 'react';

const VIRTUALIZATION_THRESHOLD = 50;

export interface VirtualListProps<T> {
  items: T[];
  renderItem: (item: T, index: number) => ReactNode;
  estimateSize?: number;
  className?: string;
  emptyContent?: ReactNode;
  overscan?: number;
}

export function VirtualList<T>({
  items,
  renderItem,
  estimateSize = 120,
  className,
  emptyContent,
  overscan = 5,
}: VirtualListProps<T>) {
  const parentRef = useRef<HTMLDivElement>(null);
  const virtualizer = useVirtualizer({
    count: items.length,
    getScrollElement: () => parentRef.current,
    estimateSize: () => estimateSize,
    overscan,
  });

  const virtualItems = virtualizer.getVirtualItems();

  if (items.length === 0) {
    return <>{emptyContent}</>;
  }

  return (
    <div ref={parentRef} className={`kd-virtual-list ${className ?? ''}`}>
      <div style={{ height: `${virtualizer.getTotalSize()}px`, position: 'relative' }}>
        {virtualItems.map((virtualItem) => (
          <div
            key={virtualItem.key}
            ref={virtualizer.measureElement}
            data-index={virtualItem.index}
            style={{
              position: 'absolute',
              top: 0,
              left: 0,
              width: '100%',
              transform: `translateY(${virtualItem.start}px)`,
            }}
          >
            {renderItem(items[virtualItem.index], virtualItem.index)}
          </div>
        ))}
      </div>
    </div>
  );
}

export function useShouldVirtualize(count: number, threshold = VIRTUALIZATION_THRESHOLD) {
  return useMemo(() => count > threshold, [count, threshold]);
}
