// desktop/src/renderer/src/knowledge-desk/components/HighlightText.tsx
interface HighlightTextProps {
  text: string;
  query: string;
  className?: string;
}

export const HighlightText = ({ text, query, className = '' }: HighlightTextProps) => {
  if (!query.trim()) {
    return <span className={className}>{text}</span>;
  }

  const tokens = query
    .trim()
    .split(/\s+/)
    .filter((token) => token.length > 0)
    .map((token) => token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));

  if (tokens.length === 0) {
    return <span className={className}>{text}</span>;
  }

  const pattern = new RegExp(`(${tokens.join('|')})`, 'gi');
  const parts = text.split(pattern);

  return (
    <span className={className}>
      {parts.map((part, index) => {
        const isMatch = tokens.some((token) => part.toLowerCase() === token.toLowerCase());
        return isMatch ? (
          <mark className="rounded-sm bg-[var(--warning-alpha-15)] px-0.5 text-[var(--accent)]" key={index}>
            {part}
          </mark>
        ) : (
          <span key={index}>{part}</span>
        );
      })}
    </span>
  );
};

// desktop/src/renderer-vue/src/knowledge-desk/components/HighlightText.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  text: string
  query: string
}>()

interface Part {
  text: string
  isMatch: boolean
}

const parts = computed<Part[]>(() => {
  const single: Part[] = [{ text: props.text, isMatch: false }]

  if (!props.query.trim()) return single

  const tokens = props.query
    .trim()
    .split(/\s+/)
    .filter((token) => token.length > 0)
    .map((token) => token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))

  if (tokens.length === 0) return single

  const pattern = new RegExp(`(${tokens.join('|')})`, 'gi')
  return props.text.split(pattern).map((part) => ({
    text: part,
    isMatch: tokens.some((token) => part.toLowerCase() === token.toLowerCase()),
  }))
})
</script>

<template>
  <span>
    <template v-for="(part, index) in parts" :key="index">
      <mark
        v-if="part.isMatch"
        class="rounded-sm bg-[var(--warning-alpha-15)] px-0.5 text-[var(--accent)]"
        >{{ part.text }}</mark
      >
      <span v-else>{{ part.text }}</span>
    </template>
  </span>
</template>
